feat: Azure Blob Storage Support
longhorn/backupstore pull request #120
Opened 2023-04-18 03:57 UTC by mantissahz

Introduce Azure blob storage support.

Ref: longhorn/longhorn#1309

2023-04-19 03:38 UTC, derekbit commented on azblob/azblob_service.go
> +	blobClient := container.NewBlockBlobClient(blob)
nil: abstract this part to a function

```suggestion
func (s *Service) newBlockBlobClient() ... {
	....
}
```

2023-04-19 03:38 UTC, derekbit commented on azblob/azblob_service.go
> +			log.Errorf("Failed to blob object: %v error: %v", blob, err)
```suggestion
			log.WithError(err).Errorf("Failed to blob object: %v", blob)
```

2023-04-19 04:12 UTC, mantissahz commented on azblob/azblob_service.go
> +	blobClient := container.NewBlockBlobClient(blob)
Addressed. Thanks

2023-04-19 04:12 UTC, mantissahz commented on azblob/azblob_service.go
> +			log.Errorf("Failed to blob object: %v error: %v", blob, err)
Modified. Thanks

2023-05-02 09:20 UTC, innobead requested changes
Please fix all comments. Thanks.

2023-05-02 09:20 UTC, innobead commented on azblob/azblob_service.go
> +	url := fmt.Sprintf(azureServiceURL, s.AccountName)
Should we need to hard code `azureServiceURL`? Is there any chance to use a customized endpoint? We support using a custom endpoint for s3.

2023-05-02 09:20 UTC, innobead commented on azblob/azblob_service.go
> +		}
Why need to collect `BlobItem` and `BlobPrefix` together? What is `BlobPrefix`? I assume what we want is `BlobItem`?

2023-05-02 09:20 UTC, innobead commented on azblob/azblob_service.go
> +func (s *Service) GetBlobProperties(blob string) (azblob.GetBlobPropertiesResponse, error) {
Change the returned variables to `*azblob.GetBlobPropertiesResponse, error`. This should apply to all methods if they will return error.

2023-05-02 09:20 UTC, innobead commented on azblob/azblob_service.go
> +		return azblob.GetBlobPropertiesResponse{}, err
`return nil, err`. The same change is for other methods after changing the returned values.

2023-05-02 09:20 UTC, innobead commented on azblob/azblob_service.go
> +		blobClient := container.NewBlockBlobClient(blob)
Why not just have one client for the service, then reused in all method calls? I know you learn from s3, but the implementation there is not good.

In this implementation, in each method call, you will create a client again and this would cause extra unnecessary cost.

2023-05-03 03:07 UTC, innobead commented
also, PR check failed.

2023-05-11 03:02 UTC, mantissahz commented on azblob/azblob_service.go
> +type Service struct {
`Service` is exported by the driver initialization now.
And removed `New` function by `NewService`.

2023-05-11 03:02 UTC, mantissahz commented on azblob/azblob.go
> +		return nil, fmt.Errorf("BUG: Why dispatch %v to %v?", u.Scheme, KIND)
Modified the error message.

2023-05-11 03:02 UTC, mantissahz commented on azblob/azblob.go
> +	}
Removed and used `NewService` in azblob_service.go instead

2023-05-11 03:02 UTC, mantissahz commented on azblob/azblob_service.go
> +	url := fmt.Sprintf(azureServiceURL, s.AccountName)
Used `AZBLOB_ENDPOINT` and `s.ServiceURL` parsed from `backup-target` URL instead.

2023-05-11 03:03 UTC, mantissahz commented on azblob/azblob_service.go
> +func (s *Service) GetBlobProperties(blob string) (azblob.GetBlobPropertiesResponse, error) {
Modified. Thanks.

2023-05-11 03:03 UTC, mantissahz commented on azblob/azblob_service.go
> +		}
Because `backupstore/volumes/02/a8/` will be only added into `BlobPrefix` and when [listing backup volumes on remote backup target](https://github.com/longhorn/backupstore/blob/master/config.go#L151-L242), it needs to list the lv1Dir `backupstore/volumes/02/` and lv2Dir `backupstore/volumes/02/a8/`.

2023-05-11 03:03 UTC, mantissahz commented on azblob/azblob_service.go
> +		return azblob.GetBlobPropertiesResponse{}, err
Modified. Thanks.

2023-05-11 03:03 UTC, mantissahz commented on azblob/azblob_service.go
> +		blobClient := container.NewBlockBlobClient(blob)
Need to get blob client for each blob but container client is modified to be initialized once.

2023-05-11 07:14 UTC, innobead commented on azblob/azblob.go
> +	if err != nil || head.ContentLength == nil {
Don't consume `err` silently. Need to log error.

2023-05-11 07:14 UTC, innobead commented on azblob/azblob.go
> +	if err != nil || blobProp.ContentLength == nil {
The same, don't silently consume `err`.

2023-05-11 07:44 UTC, innobead commented on azblob/azblob.go
> +		log.WithError(err).Error("Failed to list azblob")
No need to have this, because the error will be returned back to the caller.

2023-05-11 07:53 UTC, innobead commented on azblob/azblob_service.go
> +func (s *Service) ListBlobs(prefix, delimiter string) (*[]string, error) {
Add a comment to this method to descirbe the returned items could be blobs or blob prefixes.

2023-05-11 09:01 UTC, mantissahz commented on azblob/azblob_service.go
> +func (s *Service) ListBlobs(prefix, delimiter string) (*[]string, error) {
Added the comment to this method and other exported methods. Thanks

2023-05-11 09:01 UTC, mantissahz commented on azblob/azblob.go
> +	if err != nil || blobProp.ContentLength == nil {
Added an error log. Thanks

2023-05-11 09:01 UTC, mantissahz commented on azblob/azblob.go
> +	if err != nil || head.ContentLength == nil {
Added an error log. Thanks

2023-05-11 09:02 UTC, mantissahz commented on azblob/azblob.go
> +		log.WithError(err).Error("Failed to list azblob")
Removed. Thanks

2023-05-11 13:19 UTC, innobead requested changes

2023-05-11 13:19 UTC, innobead commented on azblob/azblob_service.go
> +func (s *service) ListBlobs(prefix, delimiter string) (*[]string, error) {
as I mentioned, don't need to export the methods of service structure. Also, is `Close()` required?

2023-05-11 14:45 UTC, mantissahz commented on azblob/azblob_service.go
> +func (s *service) ListBlobs(prefix, delimiter string) (*[]string, error) {
Modified all methods to be not exported and removed method `Close()`, yes it is not required.
Thanks

2023-05-11 14:55 UTC, innobead approved these changes

2023-05-11 15:20 UTC, merged

2023-05-16 16:31 UTC, innobead commented
@mantissahz the below code seems incorrect. We should always override `s.ServiceURL` if `azureEndpoint` is not empty, right?

[/azblob/azblob_service.go#L44-L55](https://github.com/longhorn/backupstore/blob/6183661a2bd13517f6c683d8c06fb9dd7d5baca1/azblob/azblob_service.go#L44-L55)
```go
	connStr := fmt.Sprintf(azureConnNameKey, accountName, accountKey)
	if azureEndpoint != "" {
		blobEndpointURL := strings.TrimRight(azureEndpoint, "/") + "/" + accountName
		connStr = fmt.Sprintf(connStr+blobEndpoint, blobEndpointURL)
	}

	if s.ServiceURL == "" {
		s.ServiceURL = azureURL
	}
	if s.ServiceURL != azureURL {
		connStr = connStr + fmt.Sprintf(blobEndpointSuffix, s.ServiceURL)
	}

```

2023-05-16 16:41 UTC, mantissahz commented
`azureEndpoint` will use `blobEndpoint` (`"BlobEndpoint=%s;"`)
and `s.ServiceURL` will use `blobEndpointSuffix` (`"EndpointSuffix=%s;"`) (Default `EndpointSuffix` is `azureURL `)
They will be concatenated together into `connStr`.

2023-05-16 16:57 UTC, innobead commented
You are right. It will be always respected if the value is provided.