Abstract the disk/lvol file operations in restore functions
longhorn/backupstore pull request #145
Opened 2023-08-28 08:14 UTC by derekbit

https://github.com/longhorn/longhorn/issues/6576

2023-08-30 10:04 UTC, innobead requested changes
LGTM, but some comments need to resolve. 

The dependant component repos need to be updated and backported.

2023-08-30 10:04 UTC, innobead commented on deltablock.go
> +		if stat.Mode().IsRegular() && stat.Mode()&os.ModeType == 0 {
We can just remove the duplicated `stat.Mode()&os.ModeType == 0` from this if statement. 

```go
func (m FileMode) IsRegular() bool {
	return m&ModeType == 0
}
```

2023-08-30 14:12 UTC, derekbit commented on deltablock.go
> +		if stat.Mode().IsRegular() && stat.Mode()&os.ModeType == 0 {
Updated. Thank you.

2023-08-30 14:36 UTC, derekbit commented on types.go
> +	BackendStoreDriverV2 = "v2"
Addressed. Thank you.

2023-09-01 06:17 UTC, derekbit commented
cc @innobead

2023-09-17 12:49 UTC, innobead approved these changes
LGTM. Just a few comments, but it's good to merge.

2023-09-17 12:49 UTC, innobead commented on deltablock.go
> +	log.Tracef("Creating new block file at %v", blkFile)
If we can apply the log level setting of longhorn-manager to indirectly apply to all components, then debug level should be enough.

2023-09-17 12:49 UTC, innobead commented on deltablock.go
> +		errorChans = append(errorChans, restoreBlocks(ctx, bsDriver, config.DeltaOps, config.Filename, srcVolumeName, blockChan, progress))
So incremental restore will be supported later? or we need to plan for 1.7 instead?

2023-09-17 12:49 UTC, innobead commented on deltablock.go
> +				err = fmt.Errorf("restoration is cancelled since received stop signal")
nit: Suggest adding volume name in the error message to ensure the complete error context, even though the caller could enrich the context (volume name) already at the upper layer.

2023-09-17 12:49 UTC, merged

2023-09-17 12:57 UTC, innobead commented on deltablock.go
> +	log.Tracef("Creating new block file at %v", blkFile)
ref: https://github.com/longhorn/longhorn/issues/6702