feat(backing): backingimage backup support
longhorn/backupstore pull request #146
Opened 2023-08-28 08:51 UTC by ChanYiLin

ref: [longhorn/longhorn#4165](https://github.com/longhorn/longhorn/issues/4165)

For BackingImage backup, we implemented 3 main functions
1. **CreateBackingImageBackup()**
    - with BackupBackingImageStatus interface, we can read the BackingImage data and upload it as block.
2. **RestoreBackingImageBackup()**
    - with RestoreBackingImageStatus interface, we can update the sync_file progress in `backing-image-data-source`
3. **RemoveBackingImageBackup()**

and 3 commands
- **ls-backing-image**: list all backing image names in the backupstore, so we can create the CR with `backup_target_controller`
- **inspect-backing-image**: get the info of the backup backing image, so we can sync the info the CR in the new cluster
- **rm-backing-image**: we can't implement this as grpc in `backing-image-manager`, since there might have no `backing-image-manager` pod in the cluster, so deletion can be only implemented as command and be used in the controller.

2023-09-18 10:36 UTC, ChanYiLin commented
Hi @innobead 
Refactored, thanks!

2023-12-06 07:07 UTC, derekbit commented on backupbackingimage/config.go
> +	"github.com/pkg/errors"
Reorganize the imports.

2023-12-06 07:08 UTC, derekbit commented on backupbackingimage/backupbackingimage.go
> +	"github.com/sirupsen/logrus"
Reorganize imports

2023-12-06 07:13 UTC, derekbit commented on backupbackingimage/backupbackingimage.go
> +	r, err := util.DecompressAndVerify(decompression, rc, blk.BlockChecksum)
Off the topic, we can create a ticket for ignoring the error when running into an error.
When one of blocks is somehow corrupted, we can still continue restoring the volume and don't need to error out. Then, users can still rescue the data.

2023-12-07 06:32 UTC, ChanYiLin commented on backupbackingimage/backupbackingimage.go
> +	"github.com/sirupsen/logrus"
fixed, thanks!

2023-12-07 06:33 UTC, ChanYiLin commented on backupbackingimage/backupbackingimage.go
> +	}
fixed!

2023-12-07 06:34 UTC, ChanYiLin commented on backupbackingimage/backupbackingimage.go
> +			backupStatus.Update(string(common.ProgressStateError), 0, "", err.Error())
sure, added.

2023-12-07 06:40 UTC, ChanYiLin commented on backupbackingimage/backupbackingimage.go
> +	r, err := util.DecompressAndVerify(decompression, rc, blk.BlockChecksum)
I remember this idea is from this issue: https://github.com/longhorn/longhorn/issues/7069 right?
I think we can reuse that issue to prevent duplication

2023-12-07 06:41 UTC, ChanYiLin commented on backupbackingimage/config.go
> +	"github.com/pkg/errors"
fixed, thanks

2023-12-08 09:06 UTC, shuo-wu commented on backupbackingimage/backupbackingimage.go
> +func backupMapping(bsDriver backupstore.BackupStoreDriver,
NIT: This function is unnecessary. It can be merged with `backupBlock`

2023-12-08 09:18 UTC, shuo-wu commented on backupbackingimage/backupbackingimage.go
> +		log.WithError(err).Warn("Failed to load to be deleted backup backing image")
NIT: `..., will continue the deletion"`

2023-12-08 09:49 UTC, shuo-wu commented on backupbackingimage/backupbackingimage.go
> +	if err := cleanupBlocks(bsDriver, blockInfos); err != nil {
I am thinking if it's really safe to do this without a lock, even if the backup deletion applies the same flow. What if the backup creation happens during this cleanup?

2023-12-11 07:36 UTC, ChanYiLin commented on backupbackingimage/backupbackingimage.go
> +func CreateBackingImageBackup(config *BackupConfig, backupBackingImage *BackupBackingImage, backupStatus BackupStatus, mappings *common.Mappings) (err error) {
Yeah ... I originally thought we can merge BackupVolume and BackupBackingImage together so I move the mapping creation outside the function so this function don't need to know how to read the Volume/BackingImage
 
But it seems quite impossible to merge them together.
Let me move the mapping creation back to this function.

2023-12-11 07:40 UTC, ChanYiLin commented on backupbackingimage/backupbackingimage.go
> +	backupBackingImage, err = loadBackingImage(bsDriver, backupBackingImage.Name)
Fixed, thanks

2023-12-11 07:41 UTC, ChanYiLin commented on backupbackingimage/backupbackingimage.go
> +		log.WithError(err).Warn("Failed to load to be deleted backup backing image")
Fixed, thanks!

2023-12-11 08:14 UTC, ChanYiLin commented on backupbackingimage/backupbackingimage.go
> +	}
You are right, since BackupBackingImage is not like Volume/Backup.
Every BackupBackingImage has its own and only one config. 
If there is config in the store already, we don't need to perform backup for this BackingImage

2023-12-11 08:14 UTC, ChanYiLin commented on backupbackingimage/backupbackingimage.go
> +	}
fixed, thanks

2023-12-11 08:15 UTC, ChanYiLin commented on backupbackingimage/backupbackingimage.go
> +func backupMapping(bsDriver backupstore.BackupStoreDriver,
merged, thanks

2023-12-11 08:24 UTC, ChanYiLin commented on backupbackingimage/backupbackingimage.go
> +	}
Yes, we can check its `CompleteTime` to see if it is completed or not.
If it fails to create backup from the last time, `CompleteTime` will also be empty.

2023-12-11 08:45 UTC, ChanYiLin commented on backupbackingimage/backupbackingimage.go
> +	if err := cleanupBlocks(bsDriver, blockInfos); err != nil {
We do have lock for `Create`, `Restore`, `Delete`
For `Delete` it is [here](https://github.com/longhorn/backupstore/pull/146/files#diff-ab9eae562809575c7498e159222d9cba875398859f104675b74cc04e23f7ef46R491)

as the lock design mentioned [here](https://github.com/longhorn/longhorn/blob/master/enhancements/20200701-backupstore-file-locks.md)
```
prevent backup deletion during backup restoration
prevent backup deletion while a backup is in progress
prevent backup creation during backup deletion
prevent backup restoration during backup deletion
```

2023-12-11 10:00 UTC, ChanYiLin commented on backupbackingimage/backupbackingimage.go
> +func CreateBackingImageBackup(config *BackupConfig, backupBackingImage *BackupBackingImage, backupStatus BackupStatus, mappings *common.Mappings) (err error) {
From my perspective
`backupstore` is a lib imported in `backing-image-manager` to create backingimage backup.
Mapping requires backingimage to preload() to get all the data blocks offset and its size. Currently I put the function in `backing-image-manager` [here](https://github.com/longhorn/backing-image-manager/pull/131/files#diff-90c098feebd583b6d97645040d46c9862f16fffba62b36da5010bd2cfb3e035dR235)

The reason is, from BackupVolume experience, since we put mappings creation in `backupstore`, we then need to make the interface have the functions `OpenSnapshot`, `CompareSnapshot` to create the mapping in the `backupstore` lib and avoid cycle import. And I think that makes the create backup function in `backupstore` not that general.

So I put the mappings creation in `backing-image-manager` and make the interface more general.
In the future, we can even allow other objects to be backed up by the same function simply passing its own mappings and define how to get the block data.

And since functions like `preload()` is implemented in `backing-image-manager`.
Put `CreateBackupBackingImageMappings()` in `backing-image-manager` makes more sense to me.

WDYT?

2023-12-12 08:55 UTC, shuo-wu commented on backupbackingimage/backupbackingimage.go
> +func CreateBackingImageBackup(config *BackupConfig, backupBackingImage *BackupBackingImage, backupStatus BackupStatus, mappings *common.Mappings) (err error) {
> In the future, we can even allow other objects to be backed up by the same function by simply passing its own mappings and define how to get the block data.

Good idea. I am fine with the current implementation. And I am thinking if we can modify the volume backup creation function and eliminate the interface you mentioned instead.

2023-12-12 09:15 UTC, shuo-wu approved these changes
LGTM

2023-12-15 07:39 UTC, ChanYiLin commented on backupbackingimage/backupbackingimage.go
> +func CreateBackingImageBackup(config *BackupConfig, backupBackingImage *BackupBackingImage, backupStatus BackupStatus, mappings *common.Mappings) (err error) {
Yes, I am thinking that as well, but the scope will too big.
We can do the refactor after

2023-12-20 08:30 UTC, innobead requested changes
In general, LGTM. Some comments need to resolve first.

2023-12-20 08:30 UTC, innobead commented on backupbackingimage/backupbackingimage.go
> +	r, err := util.DecompressAndVerify(decompression, rc, blk.BlockChecksum)
Let's have a ticket for that, but can be referred to 7069 if that is related.

2023-12-20 08:30 UTC, innobead commented on backupbackingimage/backupbackingimage.go
> +
As I mentioned in another comment, should add this to other functions as if they are specific for a backing image.

2023-12-20 08:30 UTC, innobead commented on backupbackingimage/backupbackingimage.go
> +		log.WithError(err).Warn("Failed to load to be deleted backup backing image config, will continue the deletion")
`"Failed to load the backup backing image config, will continue the deletion")`

2023-12-20 08:30 UTC, innobead commented on backupbackingimage/backupbackingimage.go
> +	backupbackingImageNames, err := GetAllBackupBackingImageNames(bsDriver)
`backupBackingImageNames`

2023-12-20 08:30 UTC, innobead commented on common/backup.go
> +func MergeErrorChannels(ctx context.Context, channels ...<-chan error) <-chan error {
Very interesting function.

2023-12-20 08:30 UTC, innobead commented on backupbackingimage/backupbackingimage.go
> +	}
If the deletion happens together with another upcoming new backup after `checkAndUpdateBlockInfos` check, how to prevent unexpected block deletion if those blocks are being referenced by a new backup?

How is the current backup deletion?

2023-12-26 09:31 UTC, ChanYiLin commented on backupbackingimage/backupbackingimage.go
> +func CreateBackingImageBackup(config *BackupConfig, backupBackingImage *BackupBackingImage, backupStatus BackupStatus, mappings *common.Mappings) (err error) {
Ticket: https://github.com/longhorn/longhorn/issues/7457

2023-12-26 09:50 UTC, ChanYiLin commented on backupbackingimage/backupbackingimage.go
> +}
Yes, this is actually a common function also used in backup volume
I will refactor this part in https://github.com/longhorn/longhorn/issues/7457

2023-12-26 09:55 UTC, ChanYiLin commented on common/backup.go
> +func MergeErrorChannels(ctx context.Context, channels ...<-chan error) <-chan error {
This is also a function exists in backup volume https://github.com/longhorn/backupstore/blob/master/util.go#L25
May think about how to refine it in the refactor ticket: https://github.com/longhorn/longhorn/issues/7457

2023-12-26 09:56 UTC, ChanYiLin commented on backupbackingimage/backupbackingimage.go
> +	}
There is a lock to prevent it from happening 
https://github.com/longhorn/longhorn/blob/master/enhancements/20200701-backupstore-file-locks.md#proposal

2023-12-26 10:02 UTC, ChanYiLin commented on backupbackingimage/backupbackingimage.go
> +	Update(state string, progress int, backupURL string, err string) error
rename to BackupOperation/RestoreOperation like backup volume

2023-12-26 10:05 UTC, ChanYiLin commented on backupbackingimage/backupbackingimage.go
> +	r, err := util.DecompressAndVerify(decompression, rc, blk.BlockChecksum)
ticket: https://github.com/longhorn/longhorn/issues/7458

2023-12-26 14:30 UTC, innobead requested changes
LGTM. Just one minor log change request.

2023-12-26 14:30 UTC, innobead commented on backupbackingimage/config.go
> +	return false, nil
Suggest making the log clear, like`log.Infof("Added backupstore backing image config %v", backupBackingImage.Name)` instead of `backing image`. 

Please correct other logs accordingly.

2023-12-27 01:25 UTC, ChanYiLin commented on backupbackingimage/config.go
> +	return false, nil
Sure
btw, I think with enriching log fields, we can remove the need of adding the backing image name in the log string

2023-12-27 08:37 UTC, ChanYiLin commented on backupbackingimage/config.go
> +	return false, nil
Fixed, thanks!

2023-12-27 08:39 UTC, innobead submitted a review, later dismissed

2023-12-27 09:08 UTC, innobead commented
@ChanYiLin Check the failed PR check.

2023-12-27 15:33 UTC, innobead commented
The first commit history is weird, and that could be related to how you did the rebase as discussed. I will scratch this PR instead. Please make sure the commit history and rebasing are correct in later PRs.

```
commit e1a25677b56d3f7002b73152f03595cf06f6a48f
Author: Jack Lin <jack.lin@suse.com>
Date:   Mon Aug 28 17:02:29 2023 +0800

    feat(backing): backingimage backup support
    
    ref: longhorn/longhorn 4165
    
    Signed-off-by: Jack Lin <jack.lin@suse.com>
    
    Add code to parse a query at the end of targetURL for NFS mount options.
    
    Signed-off-by: James Munson <james.munson@suse.com>
    
    Correct construction of backupURLs.
    
    Signed-off-by: James Munson <james.munson@suse.com>
    
    Address review feedback.  Add CIFS code.  Expand unit tests.
    
    Signed-off-by: James Munson <james.munson@suse.com>
    
    Revise to always keep nfsOptions during Encode and Decode BackupURL.
    
    Signed-off-by: James Munson <james.munson@suse.com>
    
    Add output to ensure test is being run.
    
    Signed-off-by: James Munson <james.munson@suse.com>
    
    feat: update golang to v1.21
    
    Signed-off-by: PoAn Yang <poan.yang@suse.com>
    
    fix(backup): Relax S3 client retry intervals
    ....
```

2023-12-27 15:46 UTC, merged