fix: skip deletion if folder does not exist
longhorn/backupstore pull request #160
Opened 2024-01-29 08:48 UTC by ChanYiLin

ref: longhorn/longhorn 7744

Since s3 doesn't support checking if folder exists.
We can use existing `getVolumeNames` which "returns all volume names based on the folders on the backupstore"
to see if the folder exists or not.

2024-01-29 09:07 UTC, ChanYiLin commented
## Test

test_basic: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6172/console
test_recurring_job_restored_from_backup_target: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6171/console

2024-01-29 09:28 UTC, derekbit commented on deltablock.go
> +	// Check if volume folder exists on backupstore
Can we move the codes into a function `DoesBackupVolumeFolderExists()` for simplifying the function?

2024-01-29 13:35 UTC, ChanYiLin commented on deltablock.go
> +	// Check if volume folder exists on backupstore
@derekbit Thanks, fixed.

2024-01-29 14:51 UTC, innobead commented
Let's make this after 1.6.0 if this is not a necessary fix. WDYT?

2024-01-30 02:31 UTC, ChanYiLin commented
> Let's make this after 1.6.0 if this is not a necessary fix. WDYT?

@innobead Agree, we can merge it later

2024-02-06 06:37 UTC, innobead requested changes
Why not just make `New` lock factory function call fail with an expected error (ex: UnsupportedLockError) and bypass the error if the driver is not filesystem-based? This way, you don't need to do any volume folder checking which needs extra resource consumption. 

[/deltablock.go#L1054-L1063](https://github.com/longhorn/backupstore/blob/9c90a8728ca2e1f95f10a4c6cf67cf7ac20c23e4/deltablock.go#L1054-L1063)
```go
	lock, err := New(bsDriver, volumeName, DELETION_LOCK)
	if err != nil {
		return err
	}

	if err := lock.Lock(); err != nil {
		return err
	}
	defer lock.Unlock()
	return removeVolume(volumeName, bsDriver)
```

2024-02-07 02:36 UTC, innobead approved these changes

2024-02-07 02:38 UTC, innobead commented
@ChanYiLin already explained the context. My previous review is invalid. LGTM.

2024-02-07 02:38 UTC, merged