Use goroutine in List API to increase performance
longhorn/backupstore pull request #63
Opened 2021-02-19 07:01 UTC by jenting

#### Proposed Changes
Since the volume backups are stored in double hashed folders.
For 1 volume backup, 3 s3 list command queries.
For 32 volume backups, the worst case is 1 + 32 + 32 = 65 s3 list command queries.

In this PR, we propose to use goroutine to increase the performance to make the queries in parallel.

#### Linked Issues
https://github.com/longhorn/longhorn/issues/1955

2021-02-22 13:28 UTC, shuo-wu requested changes

2021-02-22 13:28 UTC, shuo-wu commented on config.go
> +					names = append(names, volumeNames...)
Slice in Golang is not thread safe!

2021-02-22 13:28 UTC, shuo-wu commented on list.go
> +				errs = append(errs, err.Error())
Same here. It's not thread safe.

2021-02-22 13:28 UTC, shuo-wu commented on list.go
> +	m.Range(f)
Can we use an anonymous function instead?
```
m.Range(func(k, v interface{}) bool {
		resp[k.(string)] = v.(*VolumeInfo)
		return true
	})
```

2021-02-22 13:28 UTC, shuo-wu commented on list.go
> +		m    sync.Map // Use thread-safe sync.Map
Rename this. e.g.,`volumeInfoMap`. A variable named `m` is confusing.

2021-02-22 15:59 UTC, joshimoo commented
Good idea parallelizing the deep lookups, but instead of spawning an unbounded amount of go routines.
Consider implementing a fixed worker pool + queue approach.

Then we can pass a function to the workers + path param.
We can then use this for similar deep functions, `getBlockNamesForVolume`,
The `DeleteObjects` call can also benefit from parallel deletion.

2021-02-23 01:25 UTC, jenting commented
> Good idea parallelizing the deep lookups, but instead of spawning an unbounded amount of go routines.
> Consider implementing a fixed worker pool + queue approach.
> 
> Then we can pass a function to the workers + path param.
> We can then use this for similar deep functions, `getBlockNamesForVolume`,
> The `DeleteObjects` call can also benefit from parallel deletion.

Sounds good, I'll implement it and test the worker + queue pool performance.

2021-02-26 08:15 UTC, jenting commented
This is ready to review.

2021-02-26 16:42 UTC, joshimoo commented
@jenting Can you do a another benchmark run to see how the performance is with the fixed worker pool?

2021-02-26 17:05 UTC, joshimoo approved these changes
LGTM can probably be made a little bit more generic but we can do that in a future refactor.

2021-02-26 17:06 UTC, joshimoo commented
@shuo-wu any outstanding feedback? if not feel free to merge.

2021-03-01 12:08 UTC, shuo-wu commented on config.go
> +		payload, err := lv1Tracker.Result()
If a specific job somehow takes a long time to finish the job, will this line get blocked?

2021-03-01 12:08 UTC, shuo-wu commented on list.go
> +		payload, err := tracker.Result()
Similar question here

2021-03-01 12:30 UTC, jenting commented on config.go
> +		payload, err := lv1Tracker.Result()
Yes, this line will be blocked until the job finished (or timeout by S3 API call).

If you worried there is no default timeout value to wait for the job to be finished, we could change the worker dispatcher function from `QueueFunc` to `QueueTimedFunc`.

2021-03-01 12:44 UTC, shuo-wu commented on config.go
> +		payload, err := lv1Tracker.Result()
Yeah. It's unexpected but possible. Besides, it will affect the overall performance. I am thinking if we can:
1. Add timeout for the lv1Trackers
2. Use a buffered channel between `lv1Trackers` and this `for` loop. `lv1Trackers` always push the results to the buffer, while this `for` loop always get the latest result from the buffer then start a `lv2Tracker`.

2021-03-01 13:26 UTC, jenting commented on config.go
> +		payload, err := lv1Tracker.Result()
If I understand correctly, the goal you want to achieve is that if one of the lv1 job done and then run related lv2 job. Rather than the current implementation that waits all the lv1 jobs done and then run all the lv2 job.

Am I understand correctly?

2021-03-01 15:05 UTC, joshimoo commented on config.go
> +		payload, err := lv1Tracker.Result()
Yeah I thought about that too, but decided not to mention it since for now this implementation would be good enough.

In general it would have been nice to have a queue with n workers where we just pass in a `struct job { path string, finalDestination bool }
Then we don't need to deal with multi level trackers and instead just collect the elements where final destination == true.
The rest just keeps adding the new elements onto the job queue, till final destination == true.

Even better would be `struct job {path string, func op}`
Then as part of the op we would keep adding elements to the queue or collect the final elements.

If you want to implement that great if not, we can refactor this later.

2021-03-02 03:34 UTC, jenting commented on config.go
> +		payload, err := lv1Tracker.Result()
Personally, I'd prefer to refactor this later once we have the further issue on the list API timeout issue.

The reason I did not add the timeout for the lv1Trackers and lv2Trackers is that I want the driver layer like S3 to control the timeout itself, I remember that the S3 default timeout value is 30 seconds.

2021-03-02 03:48 UTC, shuo-wu commented on config.go
> +		payload, err := lv1Tracker.Result()
Agree. If we want to implement it and it's not complicated, we can do it later. Right now adding a timeout is the only necessary modification.

2021-03-02 05:09 UTC, jenting commented on config.go
> +		payload, err := lv1Tracker.Result()
I added a 30 seconds timeout for the job queue. Please take a look, thank u all.

2021-03-02 06:15 UTC, shuo-wu approved these changes

2021-03-02 06:15 UTC, merged