Fix delete backup memory spike
longhorn/backupstore pull request #69
Opened 2021-04-09 03:45 UTC by c3y1huang

Each volume backup is most likely to reference the same block in the storage target. And having all backups with block metadata and volume block metadata to check reference count is memory-consuming.

Remove the use of the retained backup list and process a single backup meta at a time when doing the reference check.

https://github.com/longhorn/longhorn/issues/2339

2021-04-09 10:18 UTC, c3y1huang commented
```
=== RUN   Test
DEBU[0039] GC started                                    backup=backup-4051b2211c8d48de pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0039] deleted block c78b0b0afd0acf335ae3f97963afe9caecba2394df9bff06442a8a407d9ab009 for volume DeltaBlockTestVolume  backup=backup-4051b2211c8d48de pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0039] Retained 4 blocks for volume DeltaBlockTestVolume  backup=backup-4051b2211c8d48de pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0039] Removed 1 unused blocks for volume DeltaBlockTestVolume  backup=backup-4051b2211c8d48de pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0039] GC completed                                  backup=backup-4051b2211c8d48de pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0042] GC started                                    backup=backup-34a8c5dee6a24df0 pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0042] deleted block 5f4b524e35962f33e85d95c1ae6121e4fbf5991b0fe770230da123f439d05f8e for volume DeltaBlockTestVolume  backup=backup-34a8c5dee6a24df0 pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0042] Retained 3 blocks for volume DeltaBlockTestVolume  backup=backup-34a8c5dee6a24df0 pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0042] Removed 1 unused blocks for volume DeltaBlockTestVolume  backup=backup-34a8c5dee6a24df0 pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0042] GC completed                                  backup=backup-34a8c5dee6a24df0 pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0044] GC started                                    backup=backup-f54a42a211794ae2 pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0044] Retained 2 blocks for volume DeltaBlockTestVolume  backup=backup-f54a42a211794ae2 pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0044] Removed 1 unused blocks for volume DeltaBlockTestVolume  backup=backup-f54a42a211794ae2 pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0046] GC started                                    backup=backup-d124aad87f324f1b pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0046] deleted block ac501e6a6be0b20d11a28b6df5be2b41b4db05fdcf9b5b68cfe9603dffaec9e1 for volume DeltaBlockTestVolume  backup=backup-d124aad87f324f1b pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0046] Retained 1 blocks for volume DeltaBlockTestVolume  backup=backup-d124aad87f324f1b pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0046] Removed 1 unused blocks for volume DeltaBlockTestVolume  backup=backup-d124aad87f324f1b pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0046] GC completed                                  backup=backup-d124aad87f324f1b pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0048] GC started                                    backup=backup-8db07bf5553446a1 pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0048] deleted block 224ad35246dbfac7d49c12d6ddef59fc6da3f5e46736fcef69ae12ab7779571d for volume DeltaBlockTestVolume  backup=backup-8db07bf5553446a1 pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0048] Retained 0 blocks for volume DeltaBlockTestVolume  backup=backup-8db07bf5553446a1 pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0048] Removed 1 unused blocks for volume DeltaBlockTestVolume  backup=backup-8db07bf5553446a1 pkg=backupstore volume=DeltaBlockTestVolume
DEBU[0048] GC completed                                  backup=backup-8db07bf5553446a1 pkg=backupstore volume=DeltaBlockTestVolume
OK: 1 passed
--- PASS: Test (48.62s)
PASS
ok      github.com/longhorn/backupstore/test    49.633s
```

2021-04-12 03:54 UTC, shuo-wu requested changes
I don't remember why we add the lock outside of the goroutine then release the lock inside goroutine. Let us wait for Joshua to check it.

And I am not sure why you directly use `lock.mutex` rather than `lock.Lock()`... And I don't think it's the correct way to use this file lock.

2021-04-12 03:54 UTC, shuo-wu commented on deltablock.go
> +		log.Warn("skipping block deletion, failed to load backup names")
Need to print out the error message, and mention there will be a fallback then

2021-04-12 03:54 UTC, shuo-wu commented on deltablock.go
>  		backup, err := loadBackup(name, volumeName, bsDriver)
Can you mention the issue with the GitHub link here?

2021-04-12 08:56 UTC, joshimoo requested changes
Your Lock usage is wrong, you replaced the distributed FileLock with an in memory mutex?
Have a look what the Lock/Unlock methods actually do.
https://github.com/longhorn/backupstore/blob/3f832934910ed93b3aed202ec63799b0db5af5e9/lock.go#L80

Good job on adding the tests, if you are having issues identifying the data race, let me know and I will try to help :)

Besides the lock replacement rest locks good.

2021-04-12 08:56 UTC, joshimoo commented on deltablock.go
> -	}
The reason we do this outside of the go routine, is that the lock can be thought of as a Semaphore (Counted Lock)
So we need to ensure that our Count of the Lock has been increased and persisted to the backupstore before the deferred Unlock gets called.

There is no guarantee that the GO routine has started before this function exists.

2021-04-12 08:56 UTC, joshimoo commented on deltablock.go
> +		defer lock.mutex.Unlock()
Doing the Unlock after the Close Snapshot is okay, but you need to use
`defer lock.Unlock()` so that you use the distributed lock. this applies to all the other replacements.

2021-04-12 08:56 UTC, joshimoo commented on deltablock.go
> -	}
This needs to be changed again for all the other replacements as well.

2021-04-12 08:56 UTC, joshimoo commented on deltablock.go
> +func GetLatestBackup(backup *Backup, lastBackup *Backup) error {
Do we still need to export this function?

2021-04-12 08:56 UTC, joshimoo commented on test/backup_test.go
> +	// "github.com/sirupsen/logrus"
If the logger is not used remove the comment here and below.

2021-04-12 09:55 UTC, c3y1huang commented
Moved this back to draft to fix data race.

2021-04-12 11:10 UTC, c3y1huang commented
The data race seems to be coming from the logger. Removed the lock fix commit.

2021-04-12 11:43 UTC, joshimoo reviewed
Left a comment about the latest backup selection, rest looks good to me.

2021-04-12 11:43 UTC, joshimoo commented on deltablock.go
> +		v.LastBackupAt = lastBackup.SnapshotCreatedAt
This would potentially pick an arbitrary backup, depending on processing order (i.e. errors above)
- We either need to ensure that we pick the latest backup even if we skip block deletion. (which I think is risky)
-  Unset this, in the case where we skip block deletion, since that would lead to a full backup evaluation for the next backup. (I think this should also work for the DR volume, can you verify this)

Right now I tend to think the unset the latest backup in the case where we skip block deletion and have deleted the latest backup is the better approach, since it will lead to a full backup in the worst case, while arbitrarily picking one seems worse.

2021-04-12 11:46 UTC, joshimoo commented
Leaving a note about the data race here:

That data race happened, because of an assignment to the global `log` var inside of the function.
Since this global is shared across all goroutines, it cannot be assigned to with out synchronization or a data race will happen, instead the assignment needs to happen to a new var, that can shadow the existing one. i.e. `log = X` needs to become `log := Y`
see https://github.com/longhorn/backupstore/blob/master/driver.go#L35

2021-04-12 12:30 UTC, shuo-wu commented on deltablock.go
> -	}
You mean preventing some operations like backup deletion happens after this function returns but before the go goroutine starts the actual backup creation?

2021-04-13 01:45 UTC, c3y1huang commented on deltablock.go
>  		backup, err := loadBackup(name, volumeName, bsDriver)
I've mentioned the issue just above `checkBlockReferenceCount` since the fix is mostly to resolve the large array used previously during the reference count.

2021-04-13 05:06 UTC, shuo-wu commented on deltablock.go
>  		backup, err := loadBackup(name, volumeName, bsDriver)
You mean in the commit comment? There is no comment above function `checkBlockReferenceCount`

2021-04-13 06:17 UTC, c3y1huang commented on deltablock.go
>  		backup, err := loadBackup(name, volumeName, bsDriver)
https://github.com/longhorn/backupstore/pull/69/files#diff-507431733cf7ac7a656d8e1658e89dcfc4dc30f8c76e264f648c4ce36ee1c823R839-R842

2021-04-13 06:22 UTC, c3y1huang commented on deltablock.go
> +		v.LastBackupAt = lastBackup.SnapshotCreatedAt
> * Unset this, in the case where we skip block deletion, since that would lead to a full backup evaluation for the next backup. (I think this should also work for the DR volume, can you verify this)

[Add test_backup_block_deletion_error_then_dr_restore](https://github.com/longhorn/longhorn-tests/pull/592)

2021-04-13 07:05 UTC, c3y1huang commented on deltablock.go
> +		v.LastBackupAt = lastBackup.SnapshotCreatedAt
Regression [https://ci.longhorn.io/job/private/job/longhorn-tests-regression/153/testReport/tests/test_basic/](Build#153).

2021-04-13 07:07 UTC, c3y1huang commented on deltablock.go
> +		defer lock.mutex.Unlock()
Dropped lock fix commit.

2021-04-13 07:08 UTC, c3y1huang commented on deltablock.go
> +func GetLatestBackup(backup *Backup, lastBackup *Backup) error {
No, thanks and fixed.

2021-04-13 07:08 UTC, c3y1huang commented on test/backup_test.go
> +	// "github.com/sirupsen/logrus"
Addressed.

2021-04-13 07:10 UTC, c3y1huang commented
@joshimoo , @shuo-wu , I've addressed all review comments, PTAL.

2021-04-13 09:49 UTC, joshimoo approved these changes
LGTM, I think the DR test you posted needs to be updated though, to create the DR volume then wait for restore of backup(1) before deletion of backup(1). I am assuming the DR volume will stay on backup(1) till the next backup is created, which will update lastBackup.

2021-04-13 09:54 UTC, joshimoo commented
@shuo-wu any outstanding issues?

2021-04-13 10:15 UTC, innobead approved these changes
LGTM :+1:

2021-04-13 10:20 UTC, shuo-wu commented on deltablock.go
>  		backup, err := loadBackup(name, volumeName, bsDriver)
Oh, sorry. My bad

2021-04-13 10:32 UTC, shuo-wu approved these changes
LGTM

2021-04-13 10:33 UTC, merged