List backup store volume name or backups name only
longhorn/backupstore pull request #72
Opened 2021-05-25 13:29 UTC by jenting

Signed-off-by: JenTing Hsiao <jenting.hsiao@suse.com>

2021-06-28 11:52 UTC, shuo-wu requested changes
What's the source of truth for the back volume info? The config file or the list result of the backup directory? And are the in-progress backups in neither source?

2021-06-28 11:52 UTC, shuo-wu commented on backupstore_test.go
> +			volumeName:        "-3-vol",
`vol-3`

2021-06-29 00:54 UTC, jenting commented on backupstore_test.go
> +			volumeName:        "-3-vol",
This is to test the volume name not matches the regexp `^[a-zA-Z0-9][a-zA-Z0-9_.-]+$`.

2021-06-29 03:56 UTC, shuo-wu commented on backupstore_test.go
> +			volumeName:        "-3-vol",
Got it. You can add comments for the special test cases.

2021-06-30 07:21 UTC, jenting commented
> What's the source of truth for the back volume info? The config file or the list result of the backup directory? And are the in-progress backups in neither source?

The source of truth for the backup info _must_ contains the `volume.cfg`, I've updated the PR.

The in-progress backups contains both `volume.cfg` and `backup_backup-xxx.cfg`.
We use the `CreatedTime != ""` in `backup_backup-xxx.cfg` to know it's an in progress backup or not.

2021-07-01 09:14 UTC, shuo-wu requested changes
Just curious. Is the main purpose of introducing in-mem filesystem to avoid cleanup?

2021-07-01 09:14 UTC, shuo-wu commented on list_inspect_test.go
> +	// create pvc-2 folder without metadata
`create pvc-2 folder without config file`

If Longhorn will validate the content of the config file, there can be one more case:
`create pvc-3 folder with empty config file, which is invalid`

2021-07-01 09:48 UTC, jenting commented on list.go
> +		// If the backup volume folder exist but volume.cfg not exist
I'd like to split the *list* and *read* commands.
It makes if the config file did not update, we don't have to run the *read* command since reading the config file is a time-wasted operation than the *list* command.

We make checking the content of the config file in the *read* command (**inspect-volume** or **inspect**).
Once the content of the config file is not valid (either format error _or_ in progress backup), the controller would not update the BackupVolume/Backup status.
We could make the GUI only show the BackupVolume/Backup with a non-empty status field.

2021-07-01 09:49 UTC, jenting commented on list_inspect_test.go
> +func TestInvalidList(t *testing.T) {
It's a pretty corner case that the driver not registered.

2021-07-01 10:50 UTC, jenting commented on list_inspect_test.go
> +	fs.MkdirAll(filepath.Join(backupstoreBase, VOLUME_DIRECTORY), 0755)
This makes the code simpler, I've updated it.

2021-07-01 10:53 UTC, jenting commented
> Just curious. Is the main purpose of introducing in-mem filesystem to avoid cleanup?

The purpose is to make the unit testing generate the mock folders/files more intuitive.

Previously I use a data struct to hold the backup volume and backup info.
However, I realized that it's pretty hard to know what's the current folders/files are.

2021-07-06 10:02 UTC, shuo-wu commented on list.go
> +		// If the backup volume folder exist but volume.cfg not exist
I guess you mean `the BackupVolume/Backup with an empty status field` when the content of the config file is not valid?
In general, it makes sense.

2021-07-06 10:03 UTC, shuo-wu approved these changes
LGTM.

Remember to squash commits.

2021-07-06 13:51 UTC, jenting commented on list.go
> +		// If the backup volume folder exist but volume.cfg not exist
Yes!

2021-07-06 19:44 UTC, merged