Add new API to get the config modification time
longhorn/backupstore pull request #75
Opened 2021-07-12 07:37 UTC by jenting

#### Propose Changes

- `backup config-meta`: a new command to get the config (backup volume config _or_ backup config) metadata.

#### Issue

https://github.com/longhorn/longhorn/issues/1761

2021-07-13 04:29 UTC, shuo-wu reviewed
The naming is weird... The config file store the meta info of a backup or a backup volume. But here `metadata` means the meta info of the config file itself and it reports the last modified time only...

2021-07-13 05:46 UTC, jenting commented
> The naming is weird... The config file store the meta info of a backup or a backup volume. But here `metadata` means the meta info of the config file itself and it reports the last modified time only...

If using the `head` naming, would it more intuitive? https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD

2021-07-27 09:49 UTC, shuo-wu requested changes

2021-07-27 09:49 UTC, shuo-wu commented on cmd/head.go
> +		Usage:  "get the config metadata",
`... this returns the last modification time of a config file for now.`

2021-07-27 09:49 UTC, shuo-wu commented on backupstore.go
> +func EncodeConfigURL(backupName, volumeName, destURL string) string {
`EncodeBackupURL`. Similar below

2021-07-28 00:34 UTC, jenting commented on cmd/head.go
> +		Usage:  "get the config metadata",
Add to the `description`.

2021-07-28 13:28 UTC, shuo-wu approved these changes
LGTM. Remember to rearrange the commits

2021-07-29 00:04 UTC, merged