bump go version to 1.16 and update dependencies.
longhorn/backupstore pull request #78
Opened 2021-07-26 23:58 UTC by meldafrawi

Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@suse.com>

2021-07-27 06:18 UTC, jenting commented on Dockerfile.dapper
>  ENV GOLANG_ARCH_amd64=amd64 GOLANG_ARCH_arm=armv6l GOLANG_ARCH=GOLANG_ARCH_${ARCH} \
Not quite understand this env `GOLANG_ARCH_arm=armv6l`.

2021-07-27 09:43 UTC, shuo-wu requested changes
Please rename the commit or separate the changes into multiple commits.

2021-07-27 09:43 UTC, shuo-wu commented on Dockerfile.dapper
> -    go get github.com/rancher/trash && go get -u golang.org/x/lint/golint
Is `trash` no longer required?

2021-07-27 09:58 UTC, joshimoo commented
Just to be aware go 1.16 has some module handling changes. So if you update your local go version a go get will look quite a bit different :)

https://blog.golang.org/go116-module-changes

Generally updating is a good idea once we upgrade the kubernetes version https://github.com/longhorn/longhorn/issues/2757
@meldafrawi please also create a Task issue in the longhorn/longhorn repo and reference it here as part of the PR.

2021-07-27 09:59 UTC, joshimoo commented on Dockerfile.dapper
>  ENV GOLANG_ARCH_amd64=amd64 GOLANG_ARCH_arm=armv6l GOLANG_ARCH=GOLANG_ARCH_${ARCH} \
I think this is just copy pasta from the rancher side, we don't build `armv6` images but the code can still be compiled on `armv6`

2021-08-03 20:33 UTC, meldafrawi commented on Dockerfile.dapper
> -    go get github.com/rancher/trash && go get -u golang.org/x/lint/golint
IMO, no.
According to trash docs, it's used to manage `vendor` directory, which is already achieved using `go mod` commands.

2021-08-03 20:37 UTC, meldafrawi commented on Dockerfile.dapper
>  ENV GOLANG_ARCH_amd64=amd64 GOLANG_ARCH_arm=armv6l GOLANG_ARCH=GOLANG_ARCH_${ARCH} \
@jenting, I've changed arm architecture  to `arm64`.

2021-08-04 03:03 UTC, shuo-wu commented on Dockerfile.dapper
> -    go get github.com/rancher/trash && go get -u golang.org/x/lint/golint
But it seems that `trash` is still used in Makefile. Can we remove `trash` from Makefile as well?

2022-05-26 17:02 UTC, closed without merging