feat(rollout): rollout commands
longhorn/backupstore pull request #90
Opened 2022-09-27 06:26 UTC by c3y1huang

https://github.com/longhorn/longhorn/issues/1455

2022-10-26 06:58 UTC, derekbit commented on cmd/system_backup.go
> +	sha512sum, err := util.GetFileChecksum(source)
Just curious. Why not use `sha256`? I think `sha256` is safe enough and is faster than `sha512`.

2022-10-26 06:58 UTC, derekbit commented on cmd/system_backup.go
> +		return fmt.Errorf("failed to get %v checksum: %w", source, err)
use `errors.Wrapf` instead?

2022-10-26 06:58 UTC, derekbit commented on cmd/system_backup.go
> +	return nil
```suggestion
	return systembackup.Upload(source, config)
```

2022-10-26 07:50 UTC, c3y1huang commented on cmd/system_backup.go
> +		return fmt.Errorf("failed to get %v checksum: %w", source, err)
Using `fmt.Errorf` because I want it to be consistent with other commands in this repo. And since it's the only place wrapping the error, I think its fine without the stacktrace.

WDYT @derekbit ?

2022-10-26 07:58 UTC, c3y1huang commented on cmd/system_backup.go
> +	sha512sum, err := util.GetFileChecksum(source)
Sure, we can use `sha256`, thanks for the suggestion.

I didn't think about it when writing this out because,
1. `crypto/sha512` was already imported
2. Not expecting it to be a huge file.

2022-10-26 08:07 UTC, derekbit commented on cmd/system_backup.go
> +		return fmt.Errorf("failed to get %v checksum: %w", source, err)
I see. I'm fine with it. Thank you.

2022-10-26 08:08 UTC, derekbit commented on cmd/system_backup.go
> +	sha512sum, err := util.GetFileChecksum(source)
Got it. Thank you for the explanation.

2022-11-07 12:59 UTC, innobead commented on cmd/system_backup.go
> +		return fmt.Errorf("failed to get %v checksum: %w", source, err)
I would suggest having errors.Warp in all places to make wrapped error consistent in all places.

2022-11-08 02:36 UTC, c3y1huang commented on cmd/system_backup.go
> +		return fmt.Errorf("failed to get %v checksum: %w", source, err)
> I would suggest having errors.Warp in all places to make wrapped error consistent in all places.

Addressed.

2022-11-13 16:00 UTC, innobead requested changes
In general, LGTM, but several minor places need to adjust.

2022-11-14 04:08 UTC, c3y1huang commented on systembackup/system_backup.go
> +	file := getSystemBackupConfigURI(cfg)
Updated.

2022-11-14 04:08 UTC, c3y1huang commented on systembackup/system_backup.go
> +	zipURI := getSystemBackupZipURI(cfg)
Updated.

2022-11-14 04:08 UTC, c3y1huang commented on systembackup/system_backup.go
> +		log.WithError(err).Errorf("failed to upload %v", cfg.Name)
Updated.

2022-11-14 04:09 UTC, c3y1huang commented on systembackup/system_backup.go
> +	log.Debugf("Uploaded %v", cfg.Name)
Updated.

2022-11-14 04:10 UTC, c3y1huang commented on systembackup/system_backup.go
> +		return fmt.Errorf("invalid system backup config: empty")
Updated.

2022-11-14 04:10 UTC, c3y1huang commented on systembackup/system_backup.go
> +		return fmt.Errorf("%v doesn't exist", zipURI)
Updated.

2022-11-14 04:11 UTC, c3y1huang commented on systembackup/system_backup.go
> +		os.Remove(localFilePath)
Updated.

2022-11-14 04:12 UTC, c3y1huang commented on systembackup/system_backup.go
> +	defer jobQueues.Stop()
System backup on s3 is less complex. I think we don't need this. Removed.

2022-11-14 04:12 UTC, c3y1huang commented on systembackup/system_backup.go
> +func GetSystemBackupURL(name, longhornVersion, backupTarget string) (string, error) {
Added.

2022-11-14 04:13 UTC, c3y1huang commented on systembackup/system_backup.go
> +func getSystemBackupNames(jobQueues *jobq.WorkerDispatcher, jobQueueTimeout time.Duration, driver backupstore.BackupStoreDriver) (map[string]string, error) {
I think we don't need to do the same way as `getVolumeNames`. Removed.

2022-11-14 04:13 UTC, c3y1huang commented on systembackup/system_backup.go
> +func ParseSystemBackupURL(systemBackupURL string) (backupTarget, version, name string, err error) {
Added.

2022-11-14 04:13 UTC, c3y1huang commented on config.go
> +	return loadConfigInBackupStore(filePath, driver, v)
Updated

2022-11-14 04:13 UTC, c3y1huang commented on config.go
> +	return saveConfigInBackupStore(filePath, driver, v)
Updated.

2022-11-14 04:27 UTC, innobead requested changes

2022-11-14 04:27 UTC, innobead commented on systembackup/system_backup.go
> +const jobQueueTimeout = time.Minute
Still needed?

2022-11-14 04:31 UTC, c3y1huang commented on systembackup/system_backup.go
> +const jobQueueTimeout = time.Minute
No, removed. Thanks!

2022-11-14 04:45 UTC, innobead approved these changes

2022-11-14 04:45 UTC, merged