CIFS Backup Store Support
longhorn/backupstore pull request #96
Opened 2023-01-11 03:48 UTC by derekbit

https://github.com/longhorn/longhorn/issues/3599

2023-01-13 04:45 UTC, innobead requested changes

2023-01-13 04:45 UTC, innobead commented on cifs/cifs.go
> +}
It's time to use the library. Try https://pkg.go.dev/k8s.io/mount-utils? (even though`mount-utils` is still using exec to run the system commands, but at least can leverage some existing efforts)

2023-01-13 05:14 UTC, derekbit commented on cifs/cifs.go
> +}
Looks good. Will change `nfs` and `cifs` together.

2023-01-13 15:21 UTC, derekbit commented on cifs/cifs.go
> +}
mount timeout is added `https://github.com/longhorn/backupstore/commit/2b454435af5e09ada3fa01b316b60803160b2f2d` for Harvester.

https://pkg.go.dev/k8s.io/mount-utils doesn't not support context for cancelling the stuck mount operation. Should we use `mount-utils` or keep the current method?

2023-01-16 19:23 UTC, l-mb commented on cifs/cifs.go
> +		cmd = append(cmd, "-o", fmt.Sprintf("password=%v", b.password))
This exposes the login credentials via the process list.

At the very least, please pass them via the USER/PASSWD environment variable or the credentials file parameter.

2023-01-17 01:51 UTC, derekbit commented on cifs/cifs.go
> +}
> Actually, this seems to imply there's no umount anywhere right now?

Yes

> An alternative that's easier to recover errors from is to not mount via the kernel, but use either go bindings for libsamba or run individual smbclient commands that don't touch the kernel state.

IIUC, it means we need to implement a set of file operations for the `smbclient`. Right? 

Ref: The conext of the cancellation of a mount is from this issue https://github.com/longhorn/backupstore/pull/91.

2023-01-17 14:27 UTC, derekbit commented on cifs/cifs.go
> +		cmd = append(cmd, "-o", fmt.Sprintf("password=%v", b.password))
Addressed. Thank you.

2023-01-17 14:30 UTC, l-mb commented on cifs/cifs.go
> +}
> > Actually, this seems to imply there's no umount anywhere right now?
> Yes

Could this interfere with reboots maybe? It could definitely lead to hangs until the umount times out on reboot.

> > An alternative that's easier to recover errors from is to not mount via the kernel, but use either go bindings for libsamba or run individual smbclient commands that don't touch the kernel state.
> IIUC, it means we need to implement a set of file operations for the `smbclient`. Right?

Right, this would be similar to how S3 is implemented.

> Current, except for the s3 protocol, vfs, nfs and cifs rely on the generic filesystem operations. The hanging mount rarely happened before. I think we can still use the `mount` here. In the future, we can improve it by using libsamba or smbclient instead if needed.

Yes, NFS is similar. It's rare, but has advantages in terms of robustness and kernel dependency reduction.

> Ref: The conext of the cancellation of a mount is from this issue #91.

That doesn't really cancel a mount, it merely kills the process and hopes it catches it at a time where that then indeed cleanly aborts the mount. That can be problematic if it doesn't, and then a potential retry later might not succeed, or the kernel might have dangling mounts somewhere.

`umount -f` exists, but is not as reliable.

You're right though that this is an easier approach since VFS/NFS are already implemented in a similar fashion.

2023-01-28 04:51 UTC, shuo-wu commented on cifs/cifs.go
> +	MountDir = "/var/lib/longhorn-backupstore-mounts"
NIT: should we use a dir that is different from the NFS part?

2023-01-28 04:51 UTC, shuo-wu commented on cifs/cifs.go
> +}
FYI, there is already an issue related to the stuck umount. And we mentioned in the ticket, there is no timeout/cleanup mechanism in the Kubernetes `mount-utils`:
https://github.com/longhorn/longhorn/issues/5296

2023-01-28 04:56 UTC, derekbit commented
> FYI, there is already an issue related to the stuck umount. And we mentioned in the ticket, there is no timeout/cleanup mechanism in the Kubernetes mount-utils:
https://github.com/longhorn/longhorn/issues/5296

Than you. Yeah, I've already handled this issue in the lastes update. You can check it again.

2023-01-28 04:58 UTC, derekbit commented on cifs/cifs.go
> +	MountDir = "/var/lib/longhorn-backupstore-mounts"
Because we only support one backup store, so I think using the same dir is enough.

2023-01-28 04:59 UTC, derekbit commented on cifs/cifs.go
> +}
Right. As the solution in longhorn/longhorn#5296, the force unmount is added.

2023-01-28 09:08 UTC, shuo-wu commented on util/util.go
> +		}
Is this mean `No such file or directory`? If YES, we can put `mkdir` here, which is like what func `ensureMountPoint` in longhorn-manager does.

2023-01-28 09:08 UTC, shuo-wu commented on util/util.go
> +	}
Should we check if it's a valid mount point by reading the dir? See func `ensureMountPoint` in longhorn-manager

2023-01-28 09:08 UTC, shuo-wu commented on nfs/nfs.go
> +			"soft",
Compared with the RWX volume part, we don't need the strict retry/recover mechanism hence it's fine to use soft mode, right?

2023-01-28 14:16 UTC, derekbit commented on util/util.go
> +	}
Renamed the function to `EnsureMountPoint` and added the `MkdirAll` as well. Thank you.

2023-01-28 14:17 UTC, derekbit commented on util/util.go
> +		}
Addressed. Thank you.

2023-01-28 14:17 UTC, derekbit commented on cifs/cifs.go
>  	}
Added `MountWithTimeout` for the abstraction. Thank you.

2023-01-28 14:20 UTC, derekbit commented on nfs/nfs.go
> +			"soft",
Yes. For backup, we can simply fail the backup and avoid the client getting stuck forever if the backup store is somehow broken.

2023-01-28 14:57 UTC, shuo-wu approved these changes
In general LGTM

2023-01-28 14:57 UTC, shuo-wu commented on util/util.go
> +		}
NIT: Do we still need this?

2023-01-30 01:33 UTC, derekbit commented on util/util.go
> +		}
No, we don't need it. Removed. Thank you.

2023-01-30 02:15 UTC, shuo-wu approved these changes

2023-02-07 09:26 UTC, innobead requested changes
In general, LGTM. Just some minor things needed to fix.

2023-02-07 09:26 UTC, innobead commented on util/util.go
> +			logrus.Warnf("Mount point %v was identified as corrupt by ReadDir", mountPoint)
Should include `err` in the log.

2023-02-07 09:26 UTC, innobead commented on util/util.go
> +		log.WithError(err).Warnf("Failed to check mount point %v (mounted=%v)", mountPoint, mounted)
Where is the value of `err` from? Probably no need to include `err` in this log because `err` should be handled already.

2023-02-07 09:26 UTC, innobead commented on util/util.go
> +			return true, errors.Wrapf(err, "failed to clean up corrupted mount point %v", mountPoint)
Should wrap `mntErr` instead? or just replace `mntErr` with a local `err`?

2023-02-07 09:26 UTC, innobead commented on cifs/cifs.go
> +	defaultMountTimeout  = 5 * time.Second
note: exact meaning for the const is good.

2023-02-07 14:41 UTC, derekbit commented on util/util.go
> +		log.WithError(err).Warnf("Failed to check mount point %v (mounted=%v)", mountPoint, mounted)
Sorry, forgot removing `err`.

2023-02-07 14:45 UTC, derekbit commented on util/util.go
> +			return true, errors.Wrapf(err, "failed to clean up corrupted mount point %v", mountPoint)
Fixed. Thank you.

2023-02-07 14:46 UTC, derekbit commented on util/util.go
> +		log.WithError(err).Warnf("Failed to check mount point %v (mounted=%v)", mountPoint, mounted)
Fixed. Thank you.

2023-02-07 14:46 UTC, derekbit commented on util/util.go
> +			logrus.Warnf("Mount point %v was identified as corrupt by ReadDir", mountPoint)
Fixed. Thank you.

2023-02-07 14:52 UTC, derekbit commented on cifs/cifs.go
> +	defaultMountTimeout  = 5 * time.Second
Added the relevant link for reference. Thank you.

2023-02-07 15:06 UTC, innobead commented on cifs/cifs.go
> +	defaultMountTimeout  = 5 * time.Second
I mean the variable rename is good and meaningful, so you actually don't need to do anything. This is just a note 🙂

2023-02-07 15:21 UTC, derekbit commented on cifs/cifs.go
> +	defaultMountTimeout  = 5 * time.Second
Got it. I still prefer the link here, because the 5-second timeout is dedicated for the downstream (harvester project). For other projects and developers, the short value might be confusing.

2023-02-07 15:56 UTC, innobead approved these changes

2023-02-07 15:56 UTC, merged