fix(http): proxy setting could not be changed
longhorn/backupstore pull request #97
Opened 2023-01-12 13:42 UTC by mantissahz

Proxy setting could not be changed by http.ProxyFromEnvironment after grpc server is running up.
Set our proxy function to get the proxy URL when creating a new http client for initializing s3 driver.

longhorn/longhorn#5054

2023-01-13 01:49 UTC, shuo-wu commented
> Proxy setting could not be changed by http.ProxyFromEnvironment after grpc server is running up.

Can you talk a bit more about this?

2023-01-13 02:09 UTC, mantissahz commented
>>Proxy setting could not be changed by http.ProxyFromEnvironment after grpc server is running up.

>Can you talk a bit more about this?

@shuo-wu 
Sure, 
`http.ProxyFromEnvironment` is the default setting of `Transport` to get the environment Proxy setting. https://github.com/golang/go/blob/master/src/net/http/transport.go#L43-L54
When IM-e GPRC server is running and starts to communicate with `longhorn-manager`, `Transport.Proxy` will be run only once to get the proxy setting [envProxyOnce.Do](https://github.com/golang/go/blob/master/src/net/http/transport.go#L827-L832).
Changing/Setting environment variables `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` in the GRPC server when getting the requests will not affect the `http.ProxyFromEnvironment` even creating a new client in the GRPC server

2023-01-13 04:35 UTC, innobead requested changes

2023-01-13 04:35 UTC, innobead commented on http/client.go
> +	customTransport.Proxy = proxyForURL
Why not just? Also, not just these 2 environment variables, also need to consider `NO_PROXY`, so it's better to just leverage the original lib directly. 

```go
	customTransport := http.DefaultTransport.(*http.Transport).Clone()
    customTransport.Proxy = func(request *http.Request) (*url.URL, error) {
        return httpproxy.FromEnvironment().ProxyFunc()(request.URL)
    }
    customTransport.TLSClientConfig = &tls.Config{
        InsecureSkipVerify: insecure,
        RootCAs:            certs,
    }
    client := &http.Client{Transport: customTransport}
```

2023-01-13 06:20 UTC, mantissahz commented on http/client.go
> +	customTransport.Proxy = proxyForURL
Definitely a better way. Modified and Thanks.

2023-01-13 06:33 UTC, innobead approved these changes

2023-01-13 06:58 UTC, merged

2023-01-13 07:00 UTC, mantissahz commented
Start to update longhorn-instance-manager

2023-03-06 00:07 UTC, derekbit commented
Can we create a v1.4.x branch in backupstore?
longhorn-engine still uses older commit without the backup compression improvement, but longhorn-instance-manager needs a newer one containing this commit. The difference make the dependency update a bit messy.
https://github.com/longhorn/backupstore/commits/master

cc @innobead @mantissahz

2023-03-06 00:12 UTC, innobead commented
It seems inevitable but it is definitely anti pattern. That means we probably also need for 1.3.x because it's still under maintenance.